version: '3.9'

services:

  db:
    container_name: djangodb
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 2010665KEEek

    ports:
      - 5432:5432

  web:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: erominmaksim@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 2010665KEEek

    ports:
      - 5050:80
