# Generated by Django 5.0.3 on 2024-07-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopproduct_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='reviews',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.productreview'),
        ),
    ]
