# Generated by Django 5.0.3 on 2024-07-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_product_shop_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopproduct'),
        ),
    ]
