# Generated by Django 5.0.3 on 2024-07-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_products_shop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shopproduct'),
        ),
    ]
