# Generated by Django 5.0.3 on 2024-07-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopproduct_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.shopproduct'),
        ),
    ]
