# Generated by Django 5.0.3 on 2024-07-21 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='shops', to='shop.shopproduct'),
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
