# Generated by Django 5.0.3 on 2024-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shopproduct_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='img_list',
            field=models.ImageField(upload_to='uploads/img/% Y/% m/% d/'),
        ),
    ]
