# Generated by Django 5.0.3 on 2024-07-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shopproduct_img_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimglist',
            old_name='shop',
            new_name='product',
        ),
    ]
