# Generated by Django 5.0.3 on 2024-07-21 21:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shop_product_shopproduct_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
