# Generated by Django 5.0.3 on 2024-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_shop_productimglist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='img',
            field=models.ImageField(upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='preview_image',
            field=models.ImageField(default='', upload_to='preview_img/'),
        ),
    ]
