# Generated by Django 5.0.3 on 2024-09-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_description',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
