# Generated by Django 5.0.3 on 2024-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productimglist_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='img',
            field=models.ImageField(upload_to='uploads/products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='preview_image',
            field=models.ImageField(default='', upload_to='uploads/preview_img/'),
        ),
    ]
