# Generated by Django 5.0.3 on 2024-09-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shop_shop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_description',
            new_name='company_description',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='description_company',
        ),
    ]
