# Generated by Django 5.0.3 on 2024-09-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_shop_description_shop_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_shop', to='shop.shop'),
        ),
        migrations.DeleteModel(
            name='ProductInfoMaterial',
        ),
    ]
