# Generated by Django 5.0.3 on 2024-07-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productimglist_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimglist',
            old_name='img',
            new_name='url',
        ),
    ]
