# Generated by Django 5.0.3 on 2024-07-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_img_productimglist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_list', to='shop.shopproduct'),
        ),
    ]
