# Generated by Django 5.0.3 on 2024-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_shopproduct_shop_delete_productinfomaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
    ]
