# Generated by Django 5.0.3 on 2024-09-28 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productinfo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='product_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products_info', to='shop.productinfo'),
        ),
    ]
