# Generated by Django 5.0.3 on 2024-09-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_shopproduct_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product',
        ),
    ]
