# Generated by Django 5.0.3 on 2024-07-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_productreview_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(max_length=100)),
                ('dimentions', models.CharField(max_length=100)),
                ('colours', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopproduct')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productinfomaterial')),
            ],
        ),
    ]
