# Generated by Django 5.0.3 on 2024-07-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productinfomaterial_productinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='materials',
        ),
        migrations.AddField(
            model_name='productinfomaterial',
            name='product_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='material', to='shop.productinfo'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='info', to='shop.shopproduct'),
        ),
    ]
