# Generated by Django 5.0.3 on 2024-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_productinfo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimglist',
            name='product',
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='img_list',
            field=models.ManyToManyField(blank=True, to='shop.productimglist'),
        ),
    ]
