# Generated by Django 5.0.3 on 2024-09-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_shopproduct_img_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['data']},
        ),
    ]
