# Generated by Django 5.0.3 on 2024-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_saleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='sale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
    ]
