# Generated by Django 5.0.3 on 2024-10-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_productreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productreview',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
