# Generated by Django 5.0.3 on 2024-10-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productreview_first_name_productreview_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
    ]
