# Generated by Django 5.0.3 on 2024-10-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_productreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='first_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='last_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
