# Generated by Django 5.0.3 on 2024-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productreview_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
