# Generated by Django 5.0.3 on 2024-10-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_productreview_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
    ]
