# Generated by Django 5.0.3 on 2024-10-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_productreview_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='preview_image',
        ),
    ]
