# Generated by Django 5.0.3 on 2024-10-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_shopproduct_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='preview_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preview_img', to='shop.productimglist'),
        ),
    ]
