# Generated by Django 5.0.3 on 2024-10-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_shopproduct_preview_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='preview_img',
        ),
    ]
