# Generated by Django 5.0.3 on 2024-10-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_shopproduct_preview_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='facebook_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='x_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='img_list',
            field=models.ManyToManyField(related_name='img_list', to='shop.productimglist'),
        ),
    ]
