# Generated by Django 5.0.3 on 2024-10-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_shop_facebook_link_shop_instagram_link_shop_x_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='sku',
        ),
    ]
