# Generated by Django 5.0.3 on 2024-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_remove_shopproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(blank=True, default=693, editable=False),
        ),
    ]
