# Generated by Django 5.0.3 on 2024-11-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_alter_productreview_rate_alter_shopproduct_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='img_list',
        ),
        migrations.AddField(
            model_name='productimglist',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shopproduct'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(blank=True, default=509, editable=False),
        ),
    ]
