# Generated by Django 5.0.3 on 2024-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='CzRcj5955xhiyOleCseixR9Inl3LYhbH', editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(blank=True, default=721, editable=False),
        ),
    ]
