# Generated by Django 5.0.3 on 2024-11-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_alter_productimglist_name_alter_shopproduct_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='dimentions',
            new_name='dimensions',
        ),
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='HMpcVSw0mNdhiSje7E48568kXnlSntJC', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productimglist',
            name='product',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='shop.shopproduct'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(blank=True, default=982, editable=False),
        ),
    ]
