# Generated by Django 5.0.3 on 2024-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_rename_dimentions_productinfo_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='V8gyoiN2THaHJ0x2pkhnPlbcHwHOs8Yj', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(blank=True, default=555, editable=False),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
