# Generated by Django 5.0.3 on 2024-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_productimglist_name_alter_shopproduct_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='tnDPZ2DzVPqOpNkxG9megfxqc0VVo1U8', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(default=434, editable=False),
        ),
    ]
