# Generated by Django 5.0.3 on 2024-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_productimglist_name_alter_shopproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='E3K4DO9zfJvpy371lNQt9DU3JIumYfqS', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(default=150, editable=False),
        ),
    ]
