# Generated by Django 5.0.3 on 2024-11-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_productimglist_name_alter_shopproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='0Vl7xJc9VmRysqVAeTbn1NmvVt8RhLV7', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(default=729, editable=False),
        ),
    ]
