# Generated by Django 5.0.3 on 2025-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_productimglist_name_alter_shopproduct_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimglist',
            name='name',
            field=models.CharField(default='ETqZKWHNswwA9MZV4tRbF9gEfUhyYxdA', editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='sku',
            field=models.IntegerField(default=305, editable=False),
        ),
    ]
